version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
    ports:
      - "8888:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_react_app
      MYSQL_PASSWORD: root

  backend:
    build: backend
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    links:
      - db

  nginx:
    build: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./front/build:/app:ro